ARDUINO_LIBS       = Adafruit_NeoPixel 
BOARD_TAG          = diecimila
BOARD_SUB          = atmega328
ARDUINO_PORT       = /dev/ttyUSB0
USER_LIB_PATH      = ../../libraries


include ../common.mk
include ../../arduino-mk/Arduino.mk
